### ISSUE TITLE
Auto-URL encode strings

### ISSUE THREAD

**Issue by pjlegato** [dwwoelfel/cetcd#2]
Thanks for this library, it's been helpful.

One minor point; attempting to use characters that are not allowed in URLs as arguments to the functions seems to fail. For example, `(etcd/set-key! "foo bar" 123 )` gives `URISyntaxException Illegal character in path at index 33: http://127.0.0.1:4001/v2/keys/foo bar  java.net.URI$Parser.fail (URI.java:2829)`. 

Can we alter the library to URL encode all strings before making them into URLs?

**Comment by dwwoelfel** [comment]
Good idea. I pushed it up with a new version since it will break anyone who is passing in encoded keys.
