### ISSUE TITLE
Implement conditional delete

### ISSUE THREAD

**Issue by pjlegato** [dwwoelfel/cetcd#4]
Could we extend delete-key! to support the backend's prevValue and prevExists? (https://github.com/coreos/etcd/blob/master/server/v2/delete_handler.go#L19)

I got this working with something like:

```
 (etcd/api-req :delete (->>  key url-encode (format "keys/%s"))
                                 :query-params {:prevValue old-value})
```

I'm not sure how you want to integrate the optional :prevValue argument into the cetcd API...

**Comment by dwwoelfel** [comment]
Thanks for the suggestion!

There's now a `compare-and-delete!` function, documented here: https://github.com/dwwoelfel/cetcd#compare-and-delete

You can also do

```
(etcd/delete-key! :keyname :cas {:prevValue "previous value"})
```

Not sure if `:cas` is a great name for the argument, but I copied it from the `compare-and-swap!` function to stay consistent. Now I wish I had called it `:conditions` when I started :(

**Comment by pjlegato** [comment]
It's not too late to change it! Now would be the time, before a whole lot of people are using cetcd... 
You could have it support both for a while, with :cas deprecated, and then remove it in the future.
