### ISSUE TITLE
cetcd must use http-kit >= 2.1.16 for automatic redirects from etcd to work

### ISSUE THREAD

**Issue by pjlegato** [dwwoelfel/cetcd#5]
When sending a write command to an etcd node that is not the leader (due to e.g. failover), the etcd node replies with a 307 redirect to the new leader. Unfortunately, these redirects are not implemented in http-kit versions lower than 2.1.16, so the current release of cetcd silently fails when directed to perform a write operation if it is not talking directly to the leader.

This can be fixed by bumping http-kit to 2.1.16 in project.clj.

**Comment by dwwoelfel** [comment]
Thanks! Fixed in 0.2.1
